import type { InventoryData, ProductInput } from "@/types/inventory";
export function emptyProduct(data: InventoryData): ProductInput {
  return {
    sku: "",
    barcode: "",
    retailUpc: "",
    name: "",
    description: "",
    categoryId: data.categories[0]?.id ?? "",
    brandId: data.brands[0]?.id ?? "",
    gender: "Unisex",
    concentration: "Eau de Parfum",
    sizeMl: 100,
    unit: "EA",
    packSize: 1,
    status: "active",
    color: "#b69154",
    supplier: "",
    supplierCode: "",
    averageCost: 0,
    lastCost: 0,
    retailPrice: 0,
    wholesalePrice: 0,
    vipPrice: 0,
    webPrice: 0,
    suggestedPrice: 0,
    lowestPrice: 0,
    reorderPoint: 12,
    minimumStock: 8,
    maximumStock: 120,
    daysOfStock: 30,
    taxable: true,
    taxCode: "TX-STANDARD",
    trackInventory: true,
    dropShip: false,
    labelOnReceipt: true,
    notes: "",
  };
}
